apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: e6110b808071fa82a2b63743feb13ce0e3f4d547b97fd35499382ecf0f8a3f42
    cni.projectcalico.org/podIP: 10.1.151.173/32
    cni.projectcalico.org/podIPs: 10.1.151.173/32
    prometheus.io/port: "9117"
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-11-26T10:50:22Z"
  generateName: chart-1669459821-moodle-7b49876799-
  labels:
    app.kubernetes.io/instance: chart-1669459821
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: moodle
    helm.sh/chart: moodle-14.3.2
    pod-template-hash: 7b49876799
  name: chart-1669459821-moodle-7b49876799-x9ff4
  namespace: equiz3
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: chart-1669459821-moodle-7b49876799
    uid: 7009d956-68ec-4d78-a31e-705740c842ce
  resourceVersion: "18736232"
  uid: b0676d6d-9a50-4e43-9f45-b1a395d2ce78
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: chart-1669459821
              app.kubernetes.io/name: moodle
          topologyKey: kubernetes.io/hostname
        weight: 1
  containers:
  - env:
    - name: BITNAMI_DEBUG
      value: "false"
    - name: ALLOW_EMPTY_PASSWORD
      value: "yes"
    - name: APACHE_HTTP_PORT_NUMBER
      value: "8080"
    - name: APACHE_HTTPS_PORT_NUMBER
      value: "8443"
    - name: MOODLE_DATABASE_TYPE
      value: mariadb
    - name: MOODLE_DATABASE_HOST
      value: chart-1669459821-mariadb
    - name: MOODLE_DATABASE_PORT_NUMBER
      value: "3306"
    - name: MOODLE_DATABASE_NAME
      value: bitnami_moodle
    - name: MOODLE_DATABASE_USER
      value: bn_moodle
    - name: MOODLE_HOST
      value: deep.cs.cityu.edu.hk/equiz3
    - name: CUSTOM_MOODLE_REVERSEPROXY
      value: "true"
    - name: CUSTOM_MOODLE_SSLPROXY
      value: "true"
    - name: MOODLE_DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mariadb-password
          name: chart-1669459821-mariadb
    - name: MOODLE_SKIP_BOOTSTRAP
      value: "no"
    - name: MOODLE_USERNAME
      value: admin
    - name: MOODLE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: moodle-password
          name: chart-1669459821-moodle
    - name: MOODLE_EMAIL
      value: equiz@cs.cityu.edu.hk
    image: docker.io/yzhou442/equiz-docker:latest
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 6
      httpGet:
        path: /login/index.php
        port: http
        scheme: HTTP
      initialDelaySeconds: 600
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: chart-1669459821-moodle
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    - containerPort: 8443
      name: https
      protocol: TCP
    readinessProbe:
      failureThreshold: 6
      httpGet:
        path: /login/index.php
        port: http
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      requests:
        cpu: 300m
        memory: 512Mi
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /bitnami/moodle
      name: moodle-data
      subPath: moodle
    - mountPath: /bitnami/moodledata
      name: moodle-data
      subPath: moodledata
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-4prxc
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostAliases:
  - hostnames:
    - status.localhost
    ip: 127.0.0.1
  nodeName: deep
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 0
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: moodle-data
    persistentVolumeClaim:
      claimName: chart-1669459821-moodle-moodle
  - name: kube-api-access-4prxc
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-11-26T10:50:28Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-11-26T10:52:19Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-11-26T10:52:19Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-11-26T10:50:28Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://722c6585927407b8159e5df9d5205d4bb6bcb3787ae8001eb3e8f628b6f7040f
    image: docker.io/yzhou442/equiz-docker:latest
    imageID: docker.io/yzhou442/equiz-docker@sha256:1b59812c28ce7ee8d9c04b58260cda1b7e5d86d1629bac11a05562c4dbb379c4
    lastState: {}
    name: chart-1669459821-moodle
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-11-26T10:50:29Z"
  hostIP: 144.214.120.55
  phase: Running
  podIP: 10.1.151.173
  podIPs:
  - ip: 10.1.151.173
  qosClass: Burstable
  startTime: "2022-11-26T10:50:28Z"
